### ISSUE TITLE
Milestone 2 Write-up

### ISSUE THREAD

**Issue by JustinHuPrime** [JustinHuPrime/JSCheck#2]
- [ ] Planned program analysis idea
- [ ] Changes from TA discussion
- [ ] Follow up tasks or features still to be designed
- [ ] Division of responsibilities
- [ ] Roadmap for what should be done

Remember to fill out the survey on Canvas!
