### ISSUE TITLE
Milestone 3 Write-up

### ISSUE THREAD

**Issue by JustinHuPrime** [JustinHuPrime/JSCheck#3]
- [ ] Mockup for first user study
- [ ] First user study results
- [ ] Changes to original design
- [ ] Progress against timeline

Remember to fill out the survey on Canvas!
