### ISSUE TITLE
Milestone 4 Write-up

### ISSUE THREAD

**Issue by JustinHuPrime** [JustinHuPrime/JSCheck#4]
- [ ] Status of implementation
- [ ] Plans for final user study
- [ ] Planned timeline for remaining days

Remember to fill out the survey on Canvas!
