### ISSUE TITLE
Milestone 5 Write-up

### ISSUE THREAD

**Issue by JustinHuPrime** [JustinHuPrime/JSCheck#5]
- [x] Status of final user study; feedback and changes from that
- [x] Plans for final video
- [x] Planned timeline for remaining days

Remember to fill out the survey on Canvas!
